### ISSUE TITLE
Sending Config Object Over the Wire

### ISSUE THREAD

**Issue by ayush** [typesafehub/config#1]
Thanks for writing this library and for documenting it so well. It is great and is helping us manage our config files better.

I'm using it in a system which centralizes the configuration of various other services. We need to send com.typesafe.config,Config objects over the wire to other services. What I'd like to do is the following:
1. Get string representation of a config object. Something like:
   val conf = configObject.getConfString;
2. And on the client side, simply do:
   ConfigFactory.parseString(conf)

So, my question is, given a config object, is there a simple way to get to its string representation?

**Comment by adeshrd** [comment]
@havocp 
>Also, there's a "serializable" branch now that makes config objects serializable, will be on master soon.
The Config object doesn't seem to implement Serializable interface yet. Any plans for making it serializable?
