### ISSUE TITLE
How to render a particular path's in original HOCON format, without debug comments, but with ideally original comments 

### ISSUE THREAD

**Issue by chesterxgchen** [typesafehub/config#104]
For example, if I have a config in application.conf
likes

 
sample { //use for test
   number.int.one = 1
   number.one = "1"
}

When I use the
val config = ConfigFactory.load(); 

the both system as well as samples config are loaded. 

How do I printout just the samples config in its original form ? 
The use case is this:  
    
    1) at deployment time, User like to overwrite the default configuration such as hostname, port etc. during deployment with a production configuration such as production.conf

    2) At runtime, the UI can also over write some properties, which will need to write back to disk. We decide to write back to the production.conf

   3) I don't want user to see different formats besides the changes from UI, as it will confuse users. 

    
When I use 
config.root.render(), 
it print all the values. and it has debug information for each line number. 

when I use 
config.getValue("samples").render( )
it prints the configs under "samples" scope but without "samples", and with debug line numbers. For above example, it prints out: 

{
    # alpine.core.defaults.conf: 67-68
    "number" : {
        # alpine.core.defaults.conf: 67
        "int" : {
            # alpine.core.defaults.conf: 67
            # use for test
            "one" : 1
        },
        # alpine.core.defaults.conf: 68
        "one" : "1"
    }
}

is there a way just to render to the original string format ?

thanks
Chester

**Comment by havocp** [comment]
load/edit/save is now at #272 so closing this copy
