### ISSUE TITLE
Bad parsing with semicolon at end

### ISSUE THREAD

**Issue by benmccann** [typesafehub/config#108]
In my config file I accidentally put a semi-colon at the end:

```
myprop="asfd";
```

It parsed this as myprop="asdf;" which was surprising to me. I'd think it should either result in an error or not include the semicolon

**Comment by Jonatha1983** [comment]
Hi @havocp  just wanted to double check that this was not change right ? the parsing of semicolon is still the same?
```a="b";``` 
is equal to
```a="b;"```

Thanks

**Comment by havocp** [comment]
as far as I know!

**Comment by Jonatha1983** [comment]
@havocp Thanks
