### ISSUE TITLE
Support multi-line unquoted strings

### ISSUE THREAD

**Issue by marconilanna** [typesafehub/config#11]
I know the documentation explicitly says that "multi-line unquoted strings using backslash to continue the line are not allowed". But, unless there is a good reason for not supporting it, this would be a very convenient feature.

**Comment by mig-foxbat** [comment]
@havocp any chance of getting the backtick based multi-line string that supports substitutions seeing the light of day.

**Comment by havocp** [comment]
I don't have any plans or new research here, but if someone wanted to check on what ecma ended up doing and work on a spec patch / code patch for config then they would be welcome to. I don't know how it would work out or what makes sense in advance, without doing some work myself.

**Comment by havocp** [comment]
please open a new issue to propose a direction here, with relevant links / use cases / whatever other analysis. We do ultimately need a volunteer to code it too though I don't expect it's a huge project.

**Comment by mig-foxbat** [comment]
@havocp  I have created a new issue (#391). I don't have ideas regarding the implementation as of now since I have no insights on the internal workings of this codebase.

**Comment by havocp** [comment]
Thank you. I would not expect this to be implemented without a volunteer, but it's useful to keep track of interest and ideas if nothing else.
