### ISSUE TITLE
Allow specification of default properties in code

### ISSUE THREAD

**Issue by benmccann** [typesafehub/config#110]
Play wraps the Typesafe config in a scala object in another Java object. It might make sense for Play to expose the Typesafe config to end users. The largest reason this hasn't been done is that the Play config allows specification of default properties in code while the Typesafe config does not. See a related bug in Play for some initial discussion on the topic: https://github.com/playframework/playframework/pull/2059

**Comment by havocp** [comment]
This is the same as #186 I guess so will close this copy.
