### ISSUE TITLE
Feature request: Intellij IDEA / Eclipse / Sublime Text syntax highlighting / formatting / validation for .conf (HOCON) files

### ISSUE THREAD

**Issue by eranation** [typesafehub/config#120]
I really like the HOCON notation, and it quickly became my preferred config syntax over properties, XML, JSON or YAML. 

It will be nice to have some popular text editors support so it won't just be a plain text file

Thanks

**Comment by havocp** [comment]
Will close this one since I think it's a request for other software, rather than the library itself. Happy to take specific requests for features that would be helpful though. The work for #272 could be helpful.
