### ISSUE TITLE
implement `include required("foo")` which throws an error if foo is missing

### ISSUE THREAD

**Issue by eranation** [typesafehub/config#121]
I have the following setup 

**internal.conf** with 

    include file("external.conf")
    some.prop = ${foo.bar}

**external.conf** with 

    foo.bar = x 

If external.conf is not to be found, instead of getting a helpful message such as "file not found - external.conf" I get a 

     com.typesafe.config.ConfigException$UnresolvedSubstitution: internal.conf: 2: 
        Could not resolve substitution to a value: ${foo.bar}

I think it should at least be configurable so that missing files will throw an exception *before* trying to resolve substitutions

**Comment by seantbrady** [comment]
+1 for adding a required include syntax.  I've also added #313 to help other developers avoid my plight.

**Comment by Johnlon** [comment]
I'm still interested in this issue.
I had put together a fork with the implementation we'd agreed - the amended HOCON syntax for required includes - but it's gone off the boil.
I will try to get back on it with a new patch in the next few weeks.

**Comment by havocp** [comment]
Thanks! If you get stuck on anything in the code let me know.

**Comment by patriknw** [comment]
Someone else was also interested in this feature.

**Comment by patriknw** [comment]
@Johnlon Do you have anything that we can use as a starting point for implementing this feature?

**Comment by mslinn** [comment]
+1 for the ability to fail with an exception if a required include is missing

**Comment by Johnlon** [comment]
I have a working implementation using the syntax provided on ' Oct 17, 2014' by @havocp 

If someone could review my earlier pull request (fixed tests on windows and added HOCON docs about case sensitivity) then I'll submit a pull for this new feature.

ie 

```
existing old ops ...
    include "foo.conf"
    include file("foo.conf")
    include classpath("foo.conf")
    include url("http://localhost/foo.conf")
plus the new ops...
    include required("foo.conf")
    include required(file("foo.conf"))
    include required(classpath("foo.conf"))
    include required(url("http://localhost/foo.conf"))
```

**Comment by patriknw** [comment]
thanks @Johnlon

**Comment by Johnlon** [comment]
OK third attempt see .. https://github.com/typesafehub/config/pull/421

**Comment by Johnlon** [comment]
Presumably this ticket is now closed??

**Comment by havocp** [comment]
Yep

**Comment by mslinn** [comment]
Can't wait to use this in production! When might a version with this new feature be released?

**Comment by Johnlon** [comment]
One thing we discussed a way back was whether the java api should allow us to make "required" the default if that's what you want.
Is there any mileage in that as a separate enhancement?

**Comment by havocp** [comment]
@mslinn let's discuss release on https://github.com/typesafehub/config/issues/420 

@Johnlon it makes me nervous to have the meaning of syntax inverted depending on API flags. Then you don't really know what a file means without knowing how the file will be loaded. Maybe another option could be a system prop or env var that says "our policy is that all include statements must have `required()` on them," so it would be an error to leave required() out. Or we could think of other choices, I don't know. Why don't we open an issue that frames the problem (a sitewide/appwide/application.conf-wide policy against optional includes?) and then we can discuss possible solutions on there.
