### ISSUE TITLE
Publish as OSGi bundle

### ISSUE THREAD

**Issue by ghost** [typesafehub/config#16]
please build as a bundle so it can be used in osgi w/o need to wrap or convert

**Comment by kevin-looft** [comment]
My project has a transitive dependency on this bundle, and I'm trying to use the maven-dependency-plugin to copy my project's dependencies at build time. However that plugin doesn't know how to handle a dependency of type 'bundle' and it results in the below error. Are there any ideas of how to avoid this?

Error: 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:copy-dependencies (copy-dependencies) on project my-project: Some problems were encountered while processing the POMs:
[ERROR] [ERROR] Unknown packaging: bundle @ line 6, column 16
[ERROR] : 1 problem was encountered while building the effective model for com.typesafe:config:1.3.1
[ERROR] [ERROR] Unknown packaging: bundle @ line 6, column 16

My pom plugin: 
            `<plugin>
                <extensions>true</extensions>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.1.1</version>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <copyPom>true</copyPom>
                            <excludeTransitive>false</excludeTransitive>
                            <addParentPoms>true</addParentPoms>
                        </configuration>
                    </execution>
                </executions>
            </plugin>`

**Comment by mpilquist** [comment]
You'll need to add the maven-bundle-plugin to your build so it is aware of the bundle package type. Take a look here: https://stackoverflow.com/questions/51069767/maven-unknown-packaging-bundle-error-from-a-dependency-packaging-as-bundle/51070617#51070617

**Comment by kevin-looft** [comment]
@mpilquist What would be the syntax in this case? I've tried a few options similar to below but they result in the same error.

 <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <extensions>true</extensions>
                <configuration>
                    <instructions>
                        <Include-Resource>
                            com.typesafe.config
                        </Include-Resource>
                    </instructions>
                </configuration>
            </plugin>

**Comment by mpilquist** [comment]
It's been a while but I think it's just this:

```xml
<build>
  <plugins>
    <plugin>
      <groupId>org.apache.felix</groupId>
      <artifactId>maven-bundle-plugin</artifactId>
      <extensions>true</extensions>
    </plugin>
  </plugins>
</build>
...
<dependencies>
  <dependency>
    <groupId>com.lightbend</groupId>
    <artifactId>config</artifactId>
    <version>...</version>
  </dependency>
</dependencies>
```
