### ISSUE TITLE
Support load-edit-save keeping formatting

### ISSUE THREAD

**Issue by David-hod** [typesafehub/config#178]
Hi, 
can you please add a new feature for supporting "edit" of configuration file.  
use case is that you read empty property and then on your code you can update keys and then store it back to the file. 
for example : 

a.conf:
p1 = 
p2 =  

code : 
Config cfg = ConfigFactory.parseFile("a.conf") 
Config updatedCfg = //manipulate cfg and edit him
updatedCfg.storeToFile(destFile)
//storeToFile api should support keeping a.conf exactly as it was i.e keep brackets , 
//and comments of the source file ("a.conf)

**Comment by havocp** [comment]
Hmm. I guess I made #272 which is the same issue but has the active discussion, so I will close this one.
I don't think we will ever support this for .properties though since we don't have a .properties parser in the library.
