### ISSUE TITLE
Support loading configuration from JNDI 

### ISSUE THREAD

**Issue by orangy** [typesafehub/config#221]
I'd like to use typesafe.config for my application, but it is hosted in Tomcat due to a requirement from devops. They are ok to set most configuration in .conf files, but some options they want to orchestrate in Tomcat's context config, which is accessible through JNDI. It would be nice to have a Config->JNDI bridge, so that I can just plug a JNDI context into the configuration system and do not think about different configuration places any more.

**Comment by tkawachi** [comment]
I found typesafeconfig-jndi project at https://github.com/gtri/typesafeconfig-extensions. It converts JNDI context to Config. Is it what you want? I haven't tried yet though.

**Comment by orangy** [comment]
Looks like it, thanks! Will take a look.

**Comment by havocp** [comment]
Closing because I wouldn't do JNDI in the core; if anyone needs extensions to the core to enable stuff like this though, please open issues/PRs on the specific extensions.
