### ISSUE TITLE
Consider different substitution character-don't conflict w/Scala

### ISSUE THREAD

**Issue by gzoller** [typesafehub/config#224]
The current substitution ${foo} mechanism conflicts with Scala's string interpolation:

val stuff = "hey"
val c = s"""foo {
   bar:${something}
   other: $stuff
}"""
val cfg = ConfigFactory.parseString(c)

Since both Scala and Config are looking for '$' they get confused (actually Scala gets confused).  Optionally supporting another character besides '$' would avoid the confusion.

**Comment by havocp** [comment]
I think `$$` is as good as anything I can think of, so closing for now, anyone feel free to discuss the topic though.
