### ISSUE TITLE
rendered keys of an object should be sorted alphanumerically

### ISSUE THREAD

**Issue by derrickburns** [typesafehub/config#228]
When arrays are turned into JSON, they are represented as objects where the keys are numbers, e.g.

x {
  foo = [ "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k" ]
}

is equivalent to

x { foo {
  "0": "a"
  "1": "b"
  "2": "c"
  "3": "d"
  "4": "e"
  "5": "f"
  "6": "g"
  "7": "h"
  "8": "i"
  "9": "j"
  "10": "k"
} }

Unfortunately, when rendered this will appear as:

x { foo {
  "0": "a"
  "1": "b"
  "10": "k"
  "2": "c"
  "3": "d"
  "4": "e"
  "5": "f"
  "6": "g"
  "7": "h"
  "8": "i"
  "9": "j"
} }

The keys are sorted using the default sort.  They should be sorted using an alphanumerical comparator.

**Comment by havocp** [comment]
This shouldn't happen - arrays that are arrays should remain so. The conversion that does happen is that if you have an object with numbers for field names, you can call Config.getList and have it treated as an array.

**Comment by derrickburns** [comment]
But it does happen if you use an external file reader that flattens a file (YAML actually) into a map and then converts that map into a config.

It also happens it one uses numerical values for keys in an object

Regardless, the fix is trivial. Simply provide a comparator to the sort method that does this right thing. See my pull request on this.

**Comment by havocp** [comment]
Agreed, I'm not against trying to fix this, just checking that arrays aren't converted to objects (that would be a much more serious bug if they were, and the solution would be different from formatting objects more nicely).

**Comment by derrickburns** [comment]
I added code that is called when parseMap is used. This code will detect when maps actually encode arrays and to representing them as SimpleConfigLists instead of SimpleConfigObjects.  This lessens the need to sort map keys alphanumerically, although this is still a nice feature.
