### ISSUE TITLE
Set comments for default values

### ISSUE THREAD

**Issue by acaly** [typesafehub/config#237]
I have modified my posts here. Sorry maybe I didn't fully understand the structure of this library. I only want to add comments to those ```ConfigValue```s generated by code. I think it's a good idea to provide a way to add comments to values in those from functions (```fromMap```, ```fromAnyRef``` and others). In factory functions in ```ConfigValueFactory```, it needs one parameter to add comments to the value, like this:
```java
public static ConfigValue fromAnyRef(Object object, String originDescription, List<String> comments)
```
(or use a single String for comments.) But it's difficult to add comments to those sub values given in the map. If we can add another class ```ValueWithComments```, we can write this:
```java
Map<String, Object> configMap = new HashMap();
configMap.put("key", new ValueWithComments("value", "Comment for the entry.");
ConfigValue configValue = ConfigValueFactory.fromMap(configMap, "Default values in code", "Comment for the object.");
```
I really want to know how you think about this. Thank you very much!

**Comment by acaly** [comment]
And I wonder why comment is a part of origin, instead of a part of the value. Comments vary from value to value, even among values from a same origin. And they are usually used to make it easier for user to understand the usage of each config value. So why not store comments in value?

**Comment by havocp** [comment]
For parsing extra formats such as YAML in third-party code, we had also discussed the lack of constructors for ConfigOrigin https://github.com/typesafehub/config/pull/169#issuecomment-45568162

I do think there should be a way to do this. Maybe it is just a method on ConfigValue like `withOrigin` that modifies its origin, and methods on `ConfigOrigin` for modifying the origin itself (like `withComments`, etc.).

**Comment by acaly** [comment]
Thank you for your reply!

I have been working on a [new branch](https://github.com/acaly/config/tree/set_comments) trying to make it possible to give object/list a different origin from their entries. And now we can set comments to ```ConfigValue``` (only the ```ConfigValue``` itself, not the entries of a ```ConfigObject``` or a ```ConfigList```) when calling ```fromAnyRef```.

Besides, I also want to add support for containing ```ConfigValue``` objects in a ```Map``` or ```Iterable``` passed to ```fromAnyRef```, so we don't need to use ```withKey``` for many times. I think with these two new api, we would be able to control the origin of ```ConfigValue```s when constructing them.

**Comment by havocp** [comment]
I believe #243 solved this issue (reopen if not)
