### ISSUE TITLE
Add custom value validation feature

### ISSUE THREAD

**Issue by C-h-e-r-r-y** [typesafehub/config#238]
Sometime it is needed to ensure that typesafe contains value which satisfy some condition. For example:

    app {
        web-service-ip = 192.168.0.1
    }

In general I can set any value instead of `192.168.0.1`. It can be useful if type safe support custom validators that can be executed after typesafe is loaded. The interface can be very simple (java syntax):

    public interface Validator {
            public void validate (com.typesafe.config.Config config) throws CustomValidationException ;
    }
    
    public class ValidatorExample implements Validator {
        public void validate (com.typesafe.config.Config config) throws CustomValidationException {
            try {
                String value = config.getString("app.web-service-ip");
                InetAddress.getByName(value);
            } catch (Exception e) {
                throw new CustomValidationException("Illegal IP for value " + value );
            }
        }
    }
    
    

Validators can be attached like that:

    ConfigFactory.load().validate(new ValidatorExample())

For typseconfig there are no global changes, but for users it is very convinient to place validation code in one place.

**Comment by havocp** [comment]
The pattern I've seen for this is to validate at the point a Config is passed in to the relevant module, for example:  https://github.com/typesafehub/config/blob/master/examples/java/simple-lib/src/main/java/simplelib/SimpleLibContext.java#L22
That example just calls checkValid but it could as easily contain the validation you show here.

A real-life (Scala) example is in Akka, see their Settings object:
https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/ActorSystem.scala#L153

There the immediate calls to all getters (getString etc.) on startup force the config to at least have all the needed keys, and they could do any other validation as well.

Is there any advantage to placing the validate() method on Config itself, vs. making it a method or function in your code that takes a Config as a parameter?
`validate(ConfigFactory.load(), new ValidatorExample())` is just as short right?

**Comment by havocp** [comment]
Feel free to reopen if there's more discussion.
