### ISSUE TITLE
Ability to inspect config providers

### ISSUE THREAD

**Issue by nicky-isaacs** [typesafehub/config#247]
It would be nice, primarily for debugging purposes, to be able to inspect which providers (files, system variables etc.) were used to create a particular config

**Comment by havocp** [comment]
There are two ways now; one is to set -Dconfig.trace=loads (see README) the other is to Config.render() with the render options set up to include comments about origin. Do either of those work for you?

You can also print the origin() of a single ConfigValue.

**Comment by havocp** [comment]
Closing for now, but let me know if there's something you wanted to figure out that was difficult with the mechanisms I mentioned.
