### ISSUE TITLE
Config depends on HashMap ordering causing breakage in Java 8

### ISSUE THREAD

**Issue by benmccann** [typesafehub/config#253]
The tests fail in Java 8 and it seems to be because Java 8 has a different `Map` ordering

In Parser.java, if I change the following code:

        private AbstractConfigObject parseObject(boolean hadOpenCurly) {
            // invoked just after the OPEN_CURLY (or START, if !hadOpenCurly)
            Map<String, AbstractConfigValue> values = new HashMap<String, AbstractConfigValue>();

To this:

        private AbstractConfigObject parseObject(boolean hadOpenCurly) {
            // invoked just after the OPEN_CURLY (or START, if !hadOpenCurly)
            Map<String, AbstractConfigValue> values = new java.util.LinkedHashMap<String, AbstractConfigValue>();

Then the tests fail in Java 7. This shouldn't happen

You can notice when when printing `resolveStack` in the `ResolveContext` constructor that a different order used based upon the order of the above `Map`

**Comment by havocp** [comment]
Aha, indeed. Nice catch. If we fix this (on java 6/7) then the java 8 upgrade should go smoothly.

Possibilities: 1) the test is testing something that's actually undefined and has two valid outcomes (question: what is the failure outcome - what happens instead of what's expected), or 2) our algorithm is broken in a way that some hash orderings can hide.

**Comment by benmccann** [comment]
Yeah, I'm not sure which of those it is. I think I have to leave this to you at this point as I'm not familiar enough with the code to know what is expected here.

**Comment by benmccann** [comment]
@havocp any chance to look at this? i can't tell myself which of the two possibilities you mentioned may be the root cause

**Comment by havocp** [comment]
Decided that currently HOCON.md specifies this behavior.
