### ISSUE TITLE
1.2.1 - 'SimpleConfigList created with wrong resolve status' error despite load with allowUnresolved=true

### ISSUE THREAD

**Issue by chaaaaaarlie** [typesafehub/config#281]
Sorry for the clunky description - it's tough to articulate the problem I've encountered. Essentially, `ConfigFactory.load` is throwing an resolve error when building a list that includes a concatenated value referencing a field from an inherited config, even when `allowUnresolved` is set. This only occurs when the concatenated value is in a list; everything works fine when the value is alone or inside of an object. Loading the config with `ConfigFactory.parseResources()` or `ConfigFactory.parseFile()` works as expected. Is this a bug, or am I misunderstanding the purpose of `ConfigFactory.load()`, `ConfigResolveOptions.allowUnresolved`, or both?

Consider the following set of config files:

##### base.conf
> inheritedValue : d

##### fails.conf
>newArray :  ["abc", ${inheritedValue}"ef", "xyz"]

##### ok.conf
>newVal : ${inheritedValue}"ef"
>newObj : {field :  ${inheritedValue}"ef" }

And the following REPL session:
> scala> import com.typesafe.config._
> scala> val baseConf = ConfigFactory.load("base")
> baseConf: com.typesafe.config.Config = Config(SimpleConfigObject({"arr":["abc"], ...

Concatenation alone/in object works: 

> scala> val success  = ConfigFactory.load("ok", ConfigParseOptions.defaults, ConfigResolveOptions.defaults().setAllowUnresolved(true)).withFallback(baseConf).resolve
> success: com.typesafe.config.Config = Config(SimpleConfigObject({"arr":["abc"] ...
>scala> success.getString("newVal")
>res0: String = def
>scala> success.getObject("newObj")
>res1: com.typesafe.config.ConfigObject = SimpleConfigObject({"field":"def"})

Concatenation within list fails when built with `ConfigFactory.load()`:

>scala> val fails  = ConfigFactory.load("fails", ConfigParseOptions.defaults, ConfigResolveOptions.defaults().setAllowUnresolved(true)).withFallback(baseConf).resolve

>com.typesafe.config.ConfigException$BugOrBroken: SimpleConfigList created with wrong resolve status: SimpleConfigList(["abc",${inheritedValue}"ef","xyz"])
>	at com.typesafe.config.impl.SimpleConfigList.<init>(SimpleConfigList.java:41)
>	at com.typesafe.config.impl.SimpleConfigList.modifyMayThrow(SimpleConfigList.java:101)

List created successfully when built with `ConfigFactory.parseResources()` : 

>scala> val workaround  = ConfigFactory.parseResources("fails.conf").withFallback(baseConf).resolve
> workaround: com.typesafe.config.Config = Config(SimpleConfigObject({"arr":["abc"] ...

>scala> workaround.getStringList("newArray")
>res2: java.util.List[String] = [abc, def, xyz]

**Comment by havocp** [comment]
Apologies for the slow reply, I have been traveling. There's a very good chance this is fixed in 1.3.0-M1 (see notes at https://github.com/typesafehub/config/blob/master/NEWS.md#130-m1-march-6-2015 ) if you want to give that a try, because the resolve logic has been totally redone. If you could let me know whether 1.3.0-M1 still has the problem, I would appreciate it.

**Comment by chaaaaaarlie** [comment]
I can confirm this is fixed in 1.3.0-M1.

**Comment by havocp** [comment]
thanks very much for the report and testing!
