### ISSUE TITLE
add new ++= field separator

### ISSUE THREAD

**Issue by hepin1989** [typesafehub/config#290]
we may want to group something like:
```
load = ["data", "push", "order", "routing", "redeem", "proxy"]
```
to 
```
load ++=  ["data", "push", "order", "routing"]
load ++=["redeem"]
load += "proxy"
```

**Comment by hepin1989** [comment]
by the way ,could we get the keys in a configObject sequential?

**Comment by havocp** [comment]
https://github.com/typesafehub/config/pull/287 will allow load/edit/save of HOCON files on a syntactic level. Ordering the keys on the semantic (`com.typesafe.config.Config`) level causes a lot of problems, which are discussed on some old issue I can't find right now. In brief, it isn't clear what ordering does when two `Config` are merged, so it's no good to rely on ordering. It breaks the associativity of `withFallback`, too, and decreases efficiency.

So if you need ordering, it would be better to let me know the use-case so we can try to solve it a different way. I think load/edit/save is the common use for that and we are solving it differently already.

There's another issue open for ++= already https://github.com/typesafehub/config/issues/227

So I will close this one. thanks!

**Comment by hepin1989** [comment]
thanks for the information about ordering ,I miss the withFallback ,
looking forward to the new #287 ,we could do many good things with it.

thank you again.
