### ISSUE TITLE
1.3.0-M2 ?

### ISSUE THREAD

**Issue by benmccann** [typesafehub/config#293]
There's been a lot of changes recently. I was wondering if might make sense to have an M2? We'll probably have an RC of Play soon, so I thought it'd be good to have the latest config code before that

**Comment by havocp** [comment]
Yes. My plan is to do an M2 with the new stuff; I wanted to hoist out interfaces from some of the ConfigNode subtypes first up into public interfaces in the parser package. When is the play RC?

**Comment by benmccann** [comment]
Not exactly sure when we'll do the Play RC. @jroper might know

**Comment by havocp** [comment]
Done. (though maven central may take a few more minutes to catch up)

I did not do the interface-hoisting though. That is #300 and I decided it was enough work that I wasn't sure when it would happen.

**Comment by benmccann** [comment]
Cool. I'll update Play with this new version. Thanks!

**Comment by hepin1989** [comment]
@benmccann @havocp you are robot:P
