### ISSUE TITLE
ConfigDocument setValue to withValue

### ISSUE THREAD

**Issue by havocp** [typesafehub/config#303]
Config and ConfigOrigin use withFoo / withoutFoo instead of setFoo and removeFoo. Though ConfigParseOptions does use set I think. Rename ConfigDocument methods?

**Comment by havocp** [comment]
@fpringvaldsen any vote here? sort of torn

**Comment by fpringvaldsen** [comment]
@havocp Hmm, I'm also torn.

I think I'd probably lean towards withValue/withoutValue. I think setValue and removeValue imply that we are modifying the object on which they are being called, when in fact the object on which the method is being called is immutable.

**Comment by havocp** [comment]
I think several of these are exactly analogous to methods on Config, so we should use the same name - `withoutPath`, `withValue`, and `hasPath` are in that category. patch coming up.
