### ISSUE TITLE
Substitution error when including?

### ISSUE THREAD

**Issue by alias1** [typesafehub/config#306]
I have:
* application.conf
* reference.conf
* reference.foo.conf (which is 'root' `include`d in reference.conf (not into another key))

In reference.foo.conf I have keys `application.server.protocol`, `application.server.host`, `application.server.port`, which are then referenced from the same file to build up email text in `application.foo.email.body` using substitutions. This key is a multiline text field, with the substitutions using the 'unquoted string concat' method, eg.

```
application.foo.email.body = """
Some stuff
Happens
Here"""${application.server.protocol}"://"${application.server.host}${application.server.port}"""
Then we do some more stuff"""
```

The substitutions work fine when i make the changes to the keys in `reference.foo.conf`, but if I try and override them in `application.conf`, the email text still contains the original values from `reference.foo.conf`

My understanding of how the overlays work, and how substitution happens after all overlays, I would have expected this to work properly.

Is this a bug in config, or am I just doing something wrong somewhere along the way?

Thanks!!

**Comment by havocp** [comment]
All reference.conf files are resolved standalone, and then all application.conf are combined with the result and then the combination is resolved again. So reference.conf can't refer to application.conf, essentially. There's more discussion on https://github.com/typesafehub/config/issues/167

A possible workaround is to put an application.conf in your library along with the reference.conf, containing those things that should be processed as part of application.conf.

**Comment by alias1** [comment]
I may have been unclear, I'm not including anything in `application.conf` I'm using it in the 'proper' manner, eg. it will automagically override any keys that are set in reference files.

`reference.conf` is including `reference.foo.conf`
`application.conf` is attempting to override some default keys set in the references

**Comment by havocp** [comment]
what is the specific text that was misleading in the readme? I'll fix it up.

**Comment by alias1** [comment]
Was just looking for that now, but it seems there was no one real bit, but rather a combination of how the [standard behaviour](https://github.com/typesafehub/config#standard-behavior) and [substitutions](https://github.com/typesafehub/config#uses-of-substitutions) are described.

Maybe some kind of note in the substitution part, highlighting the thread you linked, and/or the quirks of includes/substitutions would be cool.
