### ISSUE TITLE
Config.load silently fails

### ISSUE THREAD

**Issue by cvogt** [typesafehub/config#311]
when the config file with the given name does not exist.

`ConfigFactory.load("foobar")` doesn't indicate to the users that this config in fact couldn't be loaded. Would be good to know to ease debugging. Or am I doing something wrong?

**Comment by havocp** [comment]
parseFile will fail if you just want to load one file. load allows you to just use defaults and not have any file, since it also loads all the defaults.
You can setAllowMissing(false) on the parse options for load though and I think it might require the file to exist.

**Comment by havocp** [comment]
I think the current behavior is the designed behavior, so I'll close this issue (though there may be a feature request or more discussion of solutions that comes out of it, we can make a new issue for those)
