### ISSUE TITLE
reference.conf not found in .jar files contained in a .war file's WEB-INF/lib/ 

### ISSUE THREAD

**Issue by dwalend** [typesafehub/config#314]
typesafe config's loader isn't picking up a subproject's reference.conf from within a .jar file inside a .war file's WEB_INF/lib/ .

It works fine from the .jar file. It works fine from the .war file's WEB_INF/classes (my hacky fix). 

Specifically, I'm using a spray-based servlet, and tomcat isn't picking up the spray.servlet.boot-class . However, all the spray jars are in that same lib directory, on the classpath, and complaining about the missing property. I don't think this is a spray-specific problem.

Did I just miss a key piece of the documentation?

Thanks,

Dave

**Comment by viktorklang** [comment]
Are you providing the correct ClassLoader?

**Comment by havocp** [comment]
config doesn't do anything fancy; it gets the context class loader and calls getResources on it. -Dconfig.trace=loads may be helpful for debugging.

**Comment by dwalend** [comment]
WEB_INF/classes uses a different class loader than WEB_INF/lib ?

**Comment by havocp** [comment]
I don't know offhand how wars work (haven't used them in a long time) but maybe lib is supposed to contain jars rather than files? I would ask in a forum related to the app server you're using probably to find the people who know about wars.

**Comment by dwalend** [comment]
I posted my question on the tomcat list (and someone asked for more details). Hopefully they'll be able to guide me through their classloader tree.

Thanks again for the help. If I get to the bottom of it, I'll post here for posterity.

Dave

**Comment by havocp** [comment]
thanks! good idea to post here for anyone googling in the future.

**Comment by dwalend** [comment]
I've asked on tomcat-users, got some kind responses, but no end to the mystery. I'd like to blame maven, but don't have evidence yet. I'll try some experiments over the next few days to see if I can figure out what's going on.

**Comment by havocp** [comment]
random idea: it might be easier to debug (and discuss with third parties) if you take config out of the equation and work from a test case that directly does classLoader.getResources to find a resource reference.conf

**Comment by dwalend** [comment]
I haven't been able to reproduce it by building upwards. If I get time I'll try starting with the whole SHRINE codebase and stripping it down.
