### ISSUE TITLE
Release 1.3.0 final

### ISSUE THREAD

**Issue by benmccann** [typesafehub/config#315]
Play 2.4 RC1 is out. We're going to have at least one more RC, but the final version is approaching. We're currently depending on 1.3.0-M3, but would like to have a final version soon if possible.

**Comment by havocp** [comment]
cool. what about Akka - don't you need a final 2.4.0 there?

**Comment by benmccann** [comment]
No, Akka 2.4 wasn't going to be release for another couple of months, so we decided to stop blocking on it

**Comment by havocp** [comment]
ah ok. now you are blocking on me :-) there's one open issue tagged for 1.3.0 I'd like to do. I don't think any of the open PRs are must have. can do it this week.

**Comment by benmccann** [comment]
Not blocking on you yet. There's some other stuff we need to get done as well. If you can get it done this week that'd be great!

**Comment by havocp** [comment]
Shipped it. maven central may have to sync.

**Comment by benmccann** [comment]
Thanks!
