### ISSUE TITLE
getDuration issue

### ISSUE THREAD

**Issue by zergood** [typesafehub/config#316]
I have this line in reference.conf:

    max-request-waiting-time = 3s

Code to read it:

    override def timeout = config.getDuration("max-request-waiting-time", TimeUnit.SECONDS)
    println(timeout)

It gives me:

    Timeout(3 milliseconds)

For 3m in conf it gives me Timeout(180 milliseconds). If i use TimeUnit.MICROSECONDS in getDuration it would be ok.

If you have parsing functionaly for time postfix why do I need to specify TimeUnit in getDuration? May be I don't understand something but for me conversions above seem strange. My version is 1.2.1.

**Comment by havocp** [comment]
It looks like you have a Timeout, but the code to read it you show here does not return a Timeout. So at some point you are creating the Timeout yourself, right? Do you supply the correct units to Timeout? config.getDuration in 1.2.1 returns an integer, with the units you requested, so if you create a Timeout with that integer, the Timeout will always treat it as milliseconds, right? i.e. if you ask for seconds and get 3, then do Timeout(3), you now have a timeout of 3 milliseconds.

The tests for this feature are here if you want to compare them to your code: https://github.com/typesafehub/config/blob/master/config/src/test/scala/com/typesafe/config/impl/ConfigTest.scala#L799

In 1.3.0, there's a version that returns the java 8 Duration type, which has attached units.

**Comment by zergood** [comment]
Oh.. You are right, I thought that getDuration return Duration object and that was the problem. I will close the issue.
