### ISSUE TITLE
Typesafe substitution using parametrized reference?

### ISSUE THREAD

**Issue by costimuraru** [typesafehub/config#318]
Is it possible to achieve something like this:

```
region : 2
    
regions {
    1 : us-east-1
    2 : eu-west-1
    3 : sa-east-1
}
    
# Desired outcome is `name : eu-west-1` (depending on the region value)
name : ${regions.${region}}
```

**Comment by havocp** [comment]
Not right now, but see #122 for relevant discussion

**Comment by costimuraru** [comment]
Thanks, @havocp. I also see that this issue is a duplicate of #134. Therefore, you can close this one and I'll keep an eye on the other one.
