### ISSUE TITLE
Predefine Values for Max Integer, Max Long, Infinity, etc

### ISSUE THREAD

**Issue by mslinn** [typesafehub/config#323]
The following `application.conf` entry appears to be a magic value:

    play.http.parser.maxMemoryBuffer=2147483647

... when I'm just specifying the largest possible integer. It would be great to have this predefined as a value:

    play.http.parser.maxMemoryBuffer=MaxInt

... or whatever syntax makes the most sense

    play.http.parser.maxMemoryBuffer=Integer.maxValue

**Comment by havocp** [comment]
The way I'd probably do this is to have a reference.conf containing something like:
```
Constants {
  MaxInt = 2147483647
}
```

or whatever you want to call it, and then reference these as `${Constants.MaxInt}` etc.

Maybe a good starting point would be for someone to put this together as a single .conf file that anyone can drop in their project. Maybe it should come with the library, would have to think about that more.

**Comment by viktorklang** [comment]
Or even:

Integer.MaxValue = 2147483647

Long.MaxValue = …


And use: ${Integer.MaxValue} :-)

On Wed, May 27, 2015 at 3:49 PM, Havoc Pennington <notifications@github.com>
wrote:

> The way I'd probably do this is to have a reference.conf containing
> something like:
>
> Constants {
>   MaxInt = 2147483647
> }
>
> or whatever you want to call it, and then reference these as
> ${Constants.MaxInt} etc.
>
> Maybe a good starting point would be for someone to put this together as a
> single .conf file that anyone can drop in their project. Maybe it should
> come with the library, would have to think about that more.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/typesafehub/config/issues/323#issuecomment-105917974>.
>



-- 
Cheers,
√

**Comment by mslinn** [comment]
`Integer.MaxValue` would be more familiar to programmers, but there might be potential confusion with the Scala predefined constant `Int.MaxValue` or the Java predefined constant `Integer.MAX_VALUE`. One solution might be to define equivalent constants called `Int.MaxValue` and `Integer.MAX_VALUE`.

**Comment by 2m** [comment]
This looks like falls into a category of concerns not of this library but of a project that uses this library. Mainly because constants such as `infinity`, `unlimited` might have different representation value depending on the context.

**Comment by mslinn** [comment]
Int.MaxValue is defined in the SLS. The constants I mentioned are not application-dependent, or hardware-dependent, thus are not context-dependent.

**Comment by cprice404** [comment]
They're language-dependent, though.

**Comment by mslinn** [comment]
Actually, they are JVM dependent. These are constants in most languages. Why not make them available?

**Comment by ktoso** [comment]
I think @havocp's solution is pretty neat – and requires no support from the library.
Note that some libs care about scala.js etc and some not, best leave defining such constants to end libraries / users IMHO.
