### ISSUE TITLE
Caching of configs is undocumented and unexpected

### ISSUE THREAD

**Issue by adamretter** [typesafehub/config#341]
README.md should mention that configs are cached, and whilst it may not be *best practice*, if you are trying to manipulate `config.resource` between JUnit tests, then really your only option is to call `ConfigFactory#invalidateCaches`.

At the moment this is undocumented and so (at least for me) unexpected behavior. I have just removed my head from the large whole in the wall I have been progressively banging it into for the last 4 hours :-(

**Comment by havocp** [comment]
It is documented in the reference manual for ConfigFactory.load: https://typesafehub.github.io/config/latest/api/com/typesafe/config/ConfigFactory.html#load--

What section of the README were you looking at? No harm in adding some mention there too perhaps.

**Comment by adamretter** [comment]
@havocp Excellent thanks
