### ISSUE TITLE
How to use $ as a key value

### ISSUE THREAD

**Issue by JayChandler** [typesafehub/config#347]
I want a config to get a Map[String, String]  where the key is a REGEX expr. and the value a string. I have to use $ and it seems to be a reserved token. How can i overcome this ?

<pre>
dtool {
	config {
		domains {
			"\.at$" =  "foo"
		}
	}
}
</pre>

**Comment by havocp** [comment]
$ should work fine as long as it's in quotes like that. what error does the example you give above throw?

Backslash could give you trouble as it would in JSON - might need to use double backslash to escape it.

**Comment by JayChandler** [comment]
Always says token $ is not allowed need to double quuote. Even with no backslash not possible

**Comment by JayChandler** [comment]
<pre>
dtool {
	config {
		partners {
			"nic.at" =  ["\\.at$"]
			
		}
	}
}
</pre>

When i try to run this code in my app
```java
appConfig.get[Map[String, List[String]]]("dtool.config.partners")
```
I get an exception

**Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'nic'**

When i try to double quote **""nic.at""** i get this error

**ConfigException$WrongType: : nic has type OBJECT rather than LIST**

All i want is to get a **Map[String, List[String]]]**

**Comment by havocp** [comment]
are you using some kind of wrapper library? there isn't a get[T] method like that in this one afaik. 

Your errors don't seem to align with the code to me. Maybe it would be helpful to provide a runnable/minimal piece of code so I can get the errors myself.

**Comment by havocp** [comment]
I suspect there's a wrapper lib with `get[T]` and it's buggy with respect to the paths vs. keys issue. Paths vs. keys is discussed in the README and in the reference docs for `Config`. The reason I think this is that `"nic"` is being looked up, instead of `"nic.at"`, which indicates that someone is parsing `nic.at` as a path when they should be treating it as a key.

**Comment by JayChandler** [comment]
Yeah i am using https://github.com/kxbmap/configs as a wrapper. I reported the same issue there seems it as bug! Maybe i try without a wrapper and look what happens. Thx for your fast response!

**Comment by JayChandler** [comment]
Added this to my build.sbt
<pre>
libraryDependencies += "com.github.kxbmap" %% "configs" % "0.2.4"
</pre>

Using this config
<pre>
dtool {
	config {
		partners {
			"nic.at" =  ["\\.at$"]
		}
	}
}
</pre>
And a simple code. 

```java
import com.github.kxbmap.configs._
import com.typesafe.config.ConfigFactory
import com.typesafe.config.Config;
import com.typesafe.config.ConfigUtil;

object Tool {
  
  def main(args: Array[String]) = {
    val appConfig = ConfigFactory.load()
    println(  appConfig.get[Map[String, List[String]]]("dtool.config.partners") );
  }
}
```

**Comment by JayChandler** [comment]
The bug has just been fixed https://github.com/kxbmap/configs/issues/7
