### ISSUE TITLE
Custom functions as substitutions

### ISSUE THREAD

**Issue by eirslett** [typesafehub/config#349]
Would it be within typesafe config's scope to support custom functions for substitution?
E.g.

```javascript
{
  foo: 3
  bar: square(3)
}
```

```java
myConfig.registerFunction("square", x -> x * x);
```

Resolving it would then become:

```javascript
{
  foo: 3
  bar: 9
}
```

If it's outside of scope, then there's no point; but if this is something that typesafe config should support, but time's the constraint, I could try to assemble a patch!

**Comment by havocp** [comment]
Offer to help is appreciated. I'd put this out of scope for a couple reasons. First I've been trying to avoid "programming" in the config file (Google has a JSON-like config language that does make that leap, blanking on what it's called right this minute). Second, any sort of registration step breaks usage by multiple modules. That is, if another module such as Akka or another lib needs config before you have registered, stuff breaks. Registration could be ok for "custom" scenarios but those are sort of not the main point of the library.
