### ISSUE TITLE
support getting finiteDuration from config

### ISSUE THREAD

**Issue by jasonf20** [typesafehub/config#351]
currently if you want a finite duration one might have to do something like the following: 

```
val finiteDuraiton = config.getDuration("time-value").toMillis millis
```

This for example would be better:
```
val finiteDuration = config.getFiniteDuration("time-value")
```

**Comment by ktoso** [comment]
That would make the library have to depend on Scala, while it's one of the goals of this library to be "zero dependencies" (to make using it in various projects, which all require typesafe-config very simple and safe).

**Comment by jasonf20** [comment]
I see. Thanks, if one day you decide to add language dependent extensions,
such as scala-extension lib this would be nice.

**Comment by havocp** [comment]
this is very simple to add in a Scala app using an implicit; search for RichConfig in README for an example.  There are also several Scala wrapper libraries linked in the README.

**Comment by ktoso** [comment]
Ah, good point about the existing wrappers Havoc, thanks :)
https://github.com/typesafehub/config#scala-wrappers-for-the-java-library

**Comment by jasonf20** [comment]
Yea, it's simple to add just thought it might be nice to have without needing to add it.

 Didn't know about the wrappers that existed already so that probably does the job. Thanks
