### ISSUE TITLE
Problem with central repo

### ISSUE THREAD

**Issue by Randgalt** [typesafehub/config#352]
> Could not find artifact com.typesafe:config:jar:1.3 in central (https://repo.maven.apache.org/maven2)

I'm using Maven 3.3.3. Here is my dep:

```xml
    <properties>
        <typesafe-config-version>1.3</typesafe-config-version>
    </properties>
...
            <dependency>
                <groupId>com.typesafe</groupId>
                <artifactId>config</artifactId>
                <version>${typesafe-config-version}</version>
            </dependency>
```

**Comment by havocp** [comment]
Apologies for not replying earlier, I missed this one. I'm guessing you figured it out by now (I don't know the problem offhand).
