### ISSUE TITLE
java.lang.UnsupportedClassVersionError: com/typesafe/config/ConfigFactory : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by StarWindMoonCloud** [typesafehub/config#358]
After upgrading to 1.3.0, it happened when calling ConfigFactory.load();
Using maven 3.3.3 and  java 1.7

**Comment by havocp** [comment]
1.3.0 requires Java 8; stick to 1.2.x for Java 6/7

**Comment by StarWindMoonCloud** [comment]
tried 1.8, looks good so far.

**Comment by 2m** [comment]
Related #379.
