### ISSUE TITLE
How to map config to json object

### ISSUE THREAD

**Issue by StarWindMoonCloud** [typesafehub/config#359]
Two ways tried here:
1. ConfigBeanFactory.create(config.getConfig(configName), classType);
But found: 
Exception in thread "main" com.typesafe.config.ConfigException$BadBean: ..., only Map<String,Object> is supported right now

2. Try to load as string, then use some json lib to map
But not able to load JSON as String.

Any suggestion? sample config

streamCards=
{
  "streamCards": {
    "foryou": [
      "profile",
      "attractive"
    ],
    "channel": [
      "channel"
    ]
  }
}

**Comment by havocp** [comment]
config.render() with the right options will give you json. check the API docs for render()

**Comment by StarWindMoonCloud** [comment]
I decided to use jackson and use json as the config file at this moment

**Comment by StarWindMoonCloud** [comment]
I checked the api: java.lang.String render(ConfigRenderOptions options). It can only yield to String, then I have to deserialize once again, can current implementation support one step config to Object conversion? 

Renders the config value to a string, using the provided options.
If the config value has not been resolved (see Config.resolve()), it's possible that it can't be rendered as valid HOCON. In that case the rendering should still be useful for debugging but you might not be able to parse it. If the value has been resolved, it will always be parseable.

If the config value has been resolved and the options disable all HOCON-specific features (such as comments), the rendering will be valid JSON. If you enable HOCON-only features such as comments, the rendering will not be valid JSON.

Parameters:
options - the rendering options
Returns:
the rendered value

**Comment by StarWindMoonCloud** [comment]
moreover, if I deserialize the string from render(), there're some comment lines (starting with "#"), that would cause excpetion like below:

Exception in thread "main" org.codehaus.jackson.JsonParseException: Unexpected character ('#' (code 35)): was expecting double-quote to start field name

**Comment by StarWindMoonCloud** [comment]
o, the previous one can be resolved by passing corresponding ConfigRenderOptions

**Comment by havocp** [comment]
if you want a Java Map try config.root().unwrapped()

**Comment by StarWindMoonCloud** [comment]
I want more than Map, arbitrary Object

**Comment by havocp** [comment]
ConfigBeanFactory?
