### ISSUE TITLE
include file("${user.home}/.service/secret.properties") ?

### ISSUE THREAD

**Issue by carrot-garden** [typesafehub/config#36]
the bible says:

https://github.com/typesafehub/config/blob/master/HOCON.md#include-syntax

"Value concatenation is NOT performed on the "argument" to include or url() etc. The argument must be a single quoted string. No substitutions are allowed, and the argument may not be an unquoted string or any other kind of value."

then what is the solution for this requirement:

include file("${user.home}/.service/secret.properties") ?

**Comment by havocp** [comment]
This is the same as #122 I think which has more discussion, so I'll close this copy.
