### ISSUE TITLE
HOCON cannot read floating point numbers without leading zeroes

### ISSUE THREAD

**Issue by KatherinePapcun** [typesafehub/config#361]
For example, it parses 0.33 as a floating-point number.  But it parses .33 as an unquoted string.

Not having the leading zero is not legitimate JSON, if we're strictly following the standard.  But I would have expected HOCON to handle this case.

This case is not listed in the documentation as far as I can see, so I'm unsure if this is intentional or just a bug.

**Comment by havocp** [comment]
I probably used the floating point grammar from json spec, which does exclude some things that parseFloat kind of functions usually allow. But it may be simple to support this and as long as we document it as another extension to json in HOCON.md that would be fine afaik.

**Comment by havocp** [comment]
If you (or anyone) were interested this is probably a straightforward patch - add a test case next to some similar cases in the tests, and make it pass. :-)

It may be an incompatible change technically if it parses as a string now, but seems like we could fudge that in practice. Most people typing `.5` probably meant to get a number.

**Comment by tkaiser** [comment]
I was going to fix this, turns out it already works as far as I can tell -- want me to just submit the PR containing some added lines in a test and some in a conf file?

**Comment by 2m** [comment]
Fixed in #363.
