### ISSUE TITLE
Unwrapped() should preserve the keys insertion orders

### ISSUE THREAD

**Issue by pkalwar** [typesafehub/config#364]
Hi,

In a peculiar scenario, i need to rely on the order of keys defined in the config file, but after getting them as map from unwrapped() object, i see its returning me a HashMap, and keys order is now lost..

In my opinion, it should return a LInkedHashMap, to preserve the keys insertion order, recursively. 

Thanks.

**Comment by havocp** [comment]
See discussion on https://github.com/typesafehub/config/issues/35 and issues linked from it.

**Comment by pkalwar** [comment]
I see. Thank you.

**Comment by havocp** [comment]
Thanks for the report btw! Appreciate that sometimes this is wanted, but as discussed on #35 I haven't been able to arrive at a satisfactory solution.
