### ISSUE TITLE
Keep same sort order

### ISSUE THREAD

**Issue by CrazyFlasher** [typesafehub/config#377]
For example I have this conf
`
{
name:"Anton"
lastName:"Crazy"
age:29
}
`
After `Config.load` I receive object with random sorted values.
This is not good for me, because I use configuration to generate protocol classes, that reads and wirtes binary data. So keeping the same order is very important.

**Comment by havocp** [comment]
https://github.com/typesafehub/config/issues/365 is the same as this issue I believe. 

The ConfigDocument API could also support this https://github.com/typesafehub/config/issues/300

Will close because the other issue is identical afaik. thanks

**Comment by CrazyFlasher** [comment]
I don't want to deeply dig to library.
Can you provide some example please?

**Comment by havocp** [comment]
There isn't a solution right now. The issues I linked to could solve it if they were fixed.
