### ISSUE TITLE
Suport properties in database

### ISSUE THREAD

**Issue by detective-conan** [typesafehub/config#392]
It's possible add support to read properties from database?
Please teach a extended point(or hint) to write custom code for database.

**Comment by havocp** [comment]
This is out-of-scope to include in the library, which deals with config values and files, but not pulling config from other sources.

What you'd do is read your data and use it to build a `Config` instance; you could put a config file in the database as a big string, or could use the JSON support of something like postgresql or Mongodb, or could write some sort of mapping from your custom db table to JSON.

I don't have an example handy, the details really depend on your goals and situation.

**Comment by detective-conan** [comment]
Thank you for your comments.
I understand the policy of the library and implementation ways.
