### ISSUE TITLE
Add getter-methods with default value

### ISSUE THREAD

**Issue by finsterwalder** [typesafehub/config#402]
Hi,

I would like to have getter-methods on config where I can supply a default value, which is chosen, when the key is not found in the config, avoiding ConfigException.Missing and all the exception handling that comes with it.

It would look like:
config.getString("key", "defaultValue")

When "key" is not found in the config, "defaultValue" is returned.

I could help to implement this. What is the sourcelevel of this project? Are you already on Java 8, since default methods on the Config interface would make this much easier.

**Comment by havocp** [comment]
I see you closed this, possibly based on the discussion in https://github.com/typesafehub/config/blob/master/README.md#how-to-handle-defaults (if not, that's the discussion I would have linked to :-) 

there's also some discussion in various past issues.

**Comment by liweys** [comment]
hmm... I did not understand the reasons. I still hope this will be supported.

**Comment by finsterwalder** [comment]
It's a matter of taste, I guess.
I also think getter methods with a default would be helpfull.
Every now and then I now need to build my own wrappers with defaults.
The users of the library should be able to decide for themselves.
I don't understand why the designers of the library force their users in this way...

**Comment by havocp** [comment]
In addition to providing this completely free library which is open source and you can change how you want, the maintainers (aka me) have written a lengthy explanation of why they don’t add two dozen ish overloaded methods that arent very useful and actively cause bugs.

If you disagree that’s fine but “force” is an absurd statement in this context. Write a utility method, fork the library and add the methods, use a different library, do what you want.

**Comment by finsterwalder** [comment]
Sorry. You are right. "Force" is too strong a statement.
And of course I did work my way around it with wrapper methods.
The problem is too small to start a fork or anything like that.
I still think the library is the best config library I know of, that's why I use it.
:smiley:

**Comment by havocp** [comment]
All good, thanks for the follow-up. 🙂
