### ISSUE TITLE
ConfigException lies about being Serializable, contains non-serializable ConfigOrigin

### ISSUE THREAD

**Issue by jedws** [typesafehub/config#42]
if we have a client report a ConfigException we get a message instead:

cannot serialize: com.typesafe.config.ConfigException$WrongType: system properties: user has type OBJECT rather than STRING))) due to java.io.NotSerializableException: com.typesafe.config.impl.SimpleConfigOrigin

seems trivial to add "implements Serializable" to either the ConfigOrigin interface or the SimpleConfigOrigin class

our ref: PERF-463

**Comment by mauhiz** [comment]
I see this issue happening in 1.2.1. It is causing trouble when Scalatest tries to serialize that exception.

**Comment by havocp** [comment]
The unit tests here pass so the bug you're seeing is somehow more specific: https://github.com/typesafehub/config/blob/master/config/src/test/scala/com/typesafe/config/impl/PublicApiTest.scala#L936

Can you open a new issue and either include info on the exact exception causing the problem, or even better provide a failing test ? Maybe easy to do copying the existing tests.

thanks for the report!

**Comment by mauhiz** [comment]
@havocp thanks for being responsive here. Please see #288
