### ISSUE TITLE
One more scala wrapper.

### ISSUE THREAD

**Issue by andr83** [typesafehub/config#429]
I did simple scala wrapper based on shapeless: https://github.com/andr83/scalaconfig. 
Can you please add link to readme?

**Comment by havocp** [comment]
Sure - want to create a PR adding it alongside the others?

**Comment by andr83** [comment]
Have created a PR: https://github.com/typesafehub/config/pull/431

**Comment by andr83** [comment]
Thank you!

**Comment by 2m** [comment]
Closed by https://github.com/typesafehub/config/pull/431
