### ISSUE TITLE
The github project description / website seems inappropriate

### ISSUE THREAD

**Issue by mslinn** [typesafehub/config#433]
The description reads: Configuration library for JVM languages

The website is: http://typesafe.com

I don't think anyone who would like to learn more about this specific project would find the cited website terribly insightful. Perhaps leave that field blank?

**Comment by ktoso** [comment]
While I see your point Mike, it's the website of the company which funds people to maintain this project... 

Why not use the field to say thanks? I'd personally do this even on personal projects to raise awareness of "oh, it's that guy", why not do this with a library and company backing it then?

**Comment by SethTisue** [comment]
how about pointing at https://typesafehub.github.io/config/ instead...?

**Comment by mslinn** [comment]
@SethTisue I think that would be appropriate

**Comment by mslinn** [comment]
lightbend.com is just as broken as typesafe.com, unless Lightbend has decided to start running ads on all their github projects. I'll step back now.

**Comment by ktoso** [comment]
We can do https://typesafehub.github.io/config/ however this requires additional work of making the docs actually available there.

**Comment by SethTisue** [comment]
@ktoso aren't they already? am I missing something?

**Comment by ktoso** [comment]
![typesafehub_config___github](https://cloud.githubusercontent.com/assets/120979/19459257/dac2330e-94d1-11e6-8354-9b89a0c79490.png)

Not really a nice page to show and direct people to 😉  Thus, I agree on directing to that site, but it should make sense, i.e. the readme be hosted there in a usable format. Which needs to be fixed before we do the link change.

**Comment by SethTisue** [comment]
unless or until something changes there, how about just not having any link at all, then? I agree with Mike that linking to typesafe.com or lightbend.com isn't helpful to the users we would like to attract. having that link there is likely to give people a lower opinion of Lightbend, not a higher one. it isn't what the URL field is for; the field has an established purpose and this isn't it.

if we want to thank or credit Lightbend for supporting the creation of the library, a better way to do that would be something in the readme.

well, I guess I'm bikeshedding a bit about a pretty small issue. you've heard my opinion, I'm fine with whatever you decide.

**Comment by havocp** [comment]
The "home page" right now is effectively the README, I would say. Thats where all the info is.

**Comment by ktoso** [comment]
So to re-iterate what I think is useful and resolves this issue: making README.md available such that it's under https://typesafehub.github.io/config/

Is this simple to do on github pages? I can try some of my nights but help would be welcome ;)

**Comment by havocp** [comment]
Check out the gh-pages branch and you can edit index.html; the reason it has a link instead of a cut-and-paste of README right now is to avoid it getting out of date. Maybe could use JS to dynamically suck in the latest README, or something like that, or just make updating it part of the release instructions in `CONTRIBUTING.md`.

**Comment by ktoso** [comment]
Yeah I'd want to avoid the gh-pages branch and the copy pasta. I believe that's doable, will attempt to find time for it tonight.

**Comment by mslinn** [comment]
[Here is a JQuery HTML includer](http://api.jquery.com/load/) that has worked well for me in the past. Usage example:

    $("#id").load("mypage.html");

**Comment by mslinn** [comment]
The [SBT Microsites Plugin](http://www.47deg.com/blog/sbt-microsites-plugin) looks like it might be useful

**Comment by ktoso** [comment]
So sadly it's not really possible to make this pain free without investing into a lot of external automation: http://stackoverflow.com/questions/15214762/how-can-i-sync-documentation-with-github-pages

Changed the link, hope the ugly page does not so nice looking page does not scare anyone away ;-)
Any help on improving it is very welcome.
