### ISSUE TITLE
Environment and System Properties not substituted in ConfigFactory.parseFile()

### ISSUE THREAD

**Issue by dylanwilder** [typesafehub/config#435]
It is unclear to me from the documentation whether or not this behavior is intended, but if I have the following:

    mykey1 = ${MY_ENVVAR}
    mykey2 = ${my.sysprop}

and load via `Config.parseFile()`, it fails with the following error whether or not i defined those values in my environment.
 
    Exception in thread "main" com.typesafe.config.ConfigException$NotResolved: need to Config#resolve() each config before using it, see the API docs for Config#resolve()
	at com.typesafe.config.impl.SimpleConfig.checkValid(SimpleConfig.java:965)
	at akka.actor.ActorSystem$Settings.<init>(ActorSystem.scala:161)
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:522)
        ...

If this is intended behavior (i.e. because parseFile is supposed to be a raw parser), what is the recommended way to load from a file baking it in to my artifacts.  I would like to be able to provide the right file at run time.  I should also mentioned that I'm using something akin to
```scala
  val config = List(
       ConfigFactory.parseFile("file1.conf"),
       ConfigFactory.parseFile("file2.conf"),
         ....
       ConfigFactory.load() // defaults
   ).reduce(_.withFallback(_))
```
As we have nested deployment environments.

**Comment by havocp** [comment]
You are missing a resolve() call.

**Comment by dylanwilder** [comment]
ah ok. makes sense. thanks!

**Comment by havocp** [comment]
You may also want to use defaultReference/defaultOverrides/defaultApplication rather than load() the main advantage is you could keep overrides (system props) on top. I think the API docs talk about what each of these are.  Should be possible to get almost any behavior desired.
