### ISSUE TITLE
java.util.Date support is undocumented

### ISSUE THREAD

**Issue by kamstrup** [typesafehub/config#438]
It took me a while to figure out that reading of java.util.Date was in fact supported. It's not mentioned anywhere Google would show me...

It appears these formats are supported: "yyyy-MM-dd'T'HH:mm:ss.SSSZ", "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", "EEE, dd MMM yyyy HH:mm:ss zzz", "yyyy-MM-dd". That's what I get in an error message at least if I try to type some garbage in a date field :-)

Not sure where this is best noted, but would be valuable info.

**Comment by havocp** [comment]
Are you sure that it is?

```
$ find -name "*.java" | xargs grep Date
$
```

I think the Date message there might be from an application or wrapper library?

**Comment by kamstrup** [comment]
Wow, you're right :-) After trying to reproduce I realized I was overlooking a line in our code that passed it through Jackson where the Date magic happened.
