### ISSUE TITLE
Would it be possible to get a new release soon?

### ISSUE THREAD

**Issue by camullen** [typesafehub/config#465]

**Comment by havocp** [comment]
Depends on the definition of "soon"? ;-) I am really swamped, a release won't take that long I guess, but there are several pending PRs that would ideally be reviewed first. Is there a specific fix you're wanting in the release?

**Comment by 2m** [comment]
v1.3.2 has been released and artifacts are in repositories.
https://github.com/typesafehub/config/blob/master/NEWS.md#132-october-6-2017
