### ISSUE TITLE
Parse TemporalAmounts besides Duration

### ISSUE THREAD

**Issue by kag0** [typesafehub/config#473]
The config currently has a handy method `getDuration` which parses readable strings like "5 minutes" into a `java.time.Duration`. 

It would be nice if there was also a way to parse other `TemporalAmount`s such as `Period` ("2 years").

**Comment by havocp** [comment]
If this supports the same units as duration (maybe adds months?) I think it would be pretty straightforward to add a getPeriod method, and I don't see a reason not to do so. The approach I'd take would be to find everywhere that has duration now and add this along the same pattern. If there are any new units added, HOCON.md would need to be updated to reflect that.
Thanks!

**Comment by kag0** [comment]
@havocp it would add days, weeks, months, and years. If you have any pointers for places to start I can look into throwing together a PR.

**Comment by havocp** [comment]
I'd essentially look at getDuration and copy that; it should have unit tests to copy also. This is a fairly "surface level" feature of the library (conversion from string or number to duration/period is late-binding when someone calls getDuration) so you wouldn't need to touch the parser or other lower level stuff afaik.

**Comment by kag0** [comment]
@havocp is there a reason the compiler targets java 6 source even though java 8 classes like `Duration` are already being used? (I was looking to use default methods in interfaces and string switches)

**Comment by havocp** [comment]
I don't remember why that is; suggest digging up the PR discussion when we switched to java 8.

**Comment by 2m** [comment]
Implemented in #478
