### ISSUE TITLE
`getConfig` doesn't work on flatened configs 

### ISSUE THREAD

**Issue by erikvanoosten** [typesafehub/config#475]
Suppose I have the following configuration:

    myapplication.kafka.in.bootstrap.servers = "localhost:9092"

Then I fetch the information with:

    val config: Config = ...
    val appConfig = config.getConfig("myapplication")
    val kafkaIn = appConfig.getConfig("kafka.in")   // throws exception
    val servers = kafkaIn.getString("bootstrap.servers")

the following exception is thrown on line 2:

    Caused by: com.typesafe.config.ConfigException$WrongType: /.../....conf: 1: kafka.in.dev.bootstrap.servers has type STRING rather than OBJECT

Work around: write the configuration as follows:

    myapplication {
        kafka.in {
            bootstrap.servers = "localhost:9092"
        }
    }

Please make it work without the work around.

**Comment by erikvanoosten** [comment]
I am sorry, it turns out it was a bug in my code.

**Comment by balajiintech** [comment]
what is the bug?

**Comment by erikvanoosten** [comment]
Sorry, memory of the problem has decayed beyond repair. Also, I no longer have access to that code.
