### ISSUE TITLE
Let ConfigFactory load from file or URL, not just resource

### ISSUE THREAD

**Issue by wsargent** [typesafehub/config#48]
I have my settings defined outside of the broad application.conf settings.

val myConfig = System.getProperty("my.config")
val config = ConfigFactory.load(myConfig)

But I can only load these files if they're defined in the classpath.  I want the option to load a configuration using loadFile or loadURL.  I can't do it from the command line either, as config.url and config.file only work with application.conf.

**Comment by Bagorolin** [comment]
It took me now quite some time to find this. All other snippets, examples and tutorials (especially if you search for HOCON just simply expect your conf file is in the resources.
Thanks for this help!
