### ISSUE TITLE
Support for variable substitution in multiline strings

### ISSUE THREAD

**Issue by hekaldama** [typesafehub/config#482]
Is there support in the HOCON spec for variable substitution in multiline strings such that:
```conf
f {
  oo = r
}

b {
  a = """${f.oo}"""
}
```
would result in:
```hocon
f {
  oo = r
}

b {
  a = r
}
```

**Comment by havocp** [comment]
Variable substitution is always outside of strings, like `"""foo"""${bar}"""baz"""`

For regular double quoted strings this is because all valid JSON should be interpreted as it is in JSON. For multiline it's for consistency.

**Comment by gemelen** [comment]
> Variable substitution is always outside of strings

Translating this to an English I'd understand: no, there is no support.

**Comment by havocp** [comment]
For total clarity:
You can do `""" something """${foo}""" something """`
You cannot do `""" something ${foo} something"""`
