### ISSUE TITLE
API changes report for Config

### ISSUE THREAD

**Issue by lvc** [typesafehub/config#500]
The review of API changes for the Config library since 0.3.1 version: https://abi-laboratory.pro/java/tracker/timeline/config/

Hope it will be helpful for users and maintainers of the library. The report is generated by the https://github.com/lvc/japi-tracker tool for jars found at http://central.maven.org/maven2/com/typesafe/config/ according to https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Thank you.

![config-2](https://user-images.githubusercontent.com/1517837/31065919-9b23e772-a751-11e7-82e8-2f7cbfc105aa.png)
![config-1](https://user-images.githubusercontent.com/1517837/31065920-9b245ef0-a751-11e7-9700-35fff6906893.png)

**Comment by 2m** [comment]
Thanks for the report!
