### ISSUE TITLE
withFallback does not replace other substituted config values

### ISSUE THREAD

**Issue by Roos12005** [typesafehub/config#501]
**---- base.conf ----**
```
value = 20
substitute {
  value = ${value}
}
```

**---- replace.conf ----**
```
value = 10
```

The result of `substitute.value` is still `20` when do `replace.withFallback(base)`.  Should it be `10`?

**Comment by ktoso** [comment]
This is documented semantics, please read: https://github.com/typesafehub/config#note-about-resolving-substitutions-in-referenceconf-and-applicationconf
