### ISSUE TITLE
Convert config file from and to Scala case class object

### ISSUE THREAD

**Issue by ngocdaothanh** [typesafehub/config#53]
It's very typesafe if it's possible to convert:

    person {
      name = Jack
      age = 20
    }

to an object of:

    case class Person(name: String, age: Int, phone: Option[String])

See:
https://github.com/json4s/json4s#serialization

**Comment by havocp** [comment]
Going to close this issue since this repo doesn't have a scala library in it :-) though I cheerlead all efforts to make nice Scala wrappers (and there's a list of them in the README that anyone is welcome to add to)
