### ISSUE TITLE
Alternative command line friendly syntax for string list

### ISSUE THREAD

**Issue by patriknw** [typesafehub/config#69]
We have the need to override string lists from command line -D parameters. That is not possible at the moment.
Example: `akka.cluster.seed-nodes=["akka.tcp://TestApp@host1:2552", "akka.tcp://TestApp@host2:2552"]`

That gives error: ConfigException$WrongType: system properties: akka.cluster.seed-nodes has type STRING rather than LIST

Some kind of alternative syntax would be nice.

As discussed the following syntax would be ok:
`-Dakka.cluster.seed-nodes.0=akka.tcp://TestApp@host1:2552 -Dakka.cluster.seed-nodes.1=akka.tcp://TestApp@host2:2552`

**Comment by RichardBradley** [comment]
This feature doesn't appear to be documented anywhere except here and http://stackoverflow.com/questions/16202501/how-can-i-override-a-typesafe-config-list-value-on-the-command-line and https://github.com/typesafehub/config/blob/f6680a5dad51d992139d45a84fad734f1778bf50/NEWS.md#101-may-19-2013 -- have I missed something?

I think it would be nice to add something to the docs about this. I'll see if I have time to make a PR in the coming weeks.

**Comment by havocp** [comment]
HOCON.md has a section about it but it's probably hard to recognize as relevant if you're looking for the answer to "how do I put a list on the command line." Something more FAQ-like in the README might be nice.
