### ISSUE TITLE
Feature Request: add extension points to implement transparent decryption of values

### ISSUE THREAD

**Issue by dimovelev** [typesafehub/config#96]
Hi,

currently there are no extension points in the library - the DefaultTransformer is a collection of static methods which cannot be extended, the path resolution is also a final not extendable class so I do not see any way how to implement a transparent decryption of encrypted values. I store sensitive data in configuration files that are checked into version control. In order to make it harder for one to guess the password, I encrypt it with standard java libraries with e.g. a symmetric key. This key is then needed to decrypt those values.
With the solution I now have (which covers some of the key features of config) there is a pre-processing step which decrypts any encrypted values. It pretty much handles two cases - values that start with {encrypted} and followed by a base64 of the encryption result and values that start with {encrypt} followed by plain text (marked for encryption).

Is there any (even dirty) hack to do that in the current config version?

Cheers,
Dimo

**Comment by jhult** [comment]
This seems related to #6.

A few options may include:

- [Facebook Conceal](https://github.com/facebook/conceal) - this might have an Android dependency
- [Jasypt](http://www.jasypt.org/) - this is old and doesn't appear to currently be updated. However, it shows what many users might desire.
